Sl 37
slimwizard/Smart-Lot pull request #14
Opened 2019-03-26 04:59 UTC by grant-freeman

This PR includes commits from SL-34 and SL-37 because I needed dev changes from SL-34 to finish my story. I've finished writing a startup script for our api, a massive function for our update, modifications to our detection model, and tests. Tests must be made with the api running.

2019-03-26 23:17 UTC, slimwizard requested changes
99% of it looks good. All I ask is that the body of the receive_image API method be broken up into separate functions like 'split_image', 'enhance_image', 'process_image'. It just doesn't make much sense from both a manageability and a readability standpoint to have a gigantic block of code handle all of those different tasks like that. Also, not sure if this was you or Charley but the Spots table's 'occupied' column and all references to it was changed to 'availability'. I don't think a parking spot's availability can be logically represented as true or false. It works better as 'occupied' or 'is_occupied', or even just 'available'.

`if (spot.occupied): do this` makes much more sense than `if (spot.availibility): do this`

Everything else looks good.

2019-03-27 00:12 UTC, Jfrachal approved these changes
Good code, only issue is getting some clarifying comments where noted. No significant issues, good to merge.

2019-03-27 00:12 UTC, Jfrachal commented on image-processing-server/detection.py
> +if cars.size:
Can you clarify what this method is doing? I'm unsure what's going on here in the context of the code. 

cars.size

2019-03-27 00:45 UTC, grant-freeman commented on image-processing-server/detection.py
> +if cars.size:
if the size of the cars array is not 0, basically

2019-03-27 01:07 UTC, slimwizard commented
Looks good

2019-03-27 01:08 UTC, merged