colorblind mode icon/toggle and night mode toggle
slimwizard/Smart-Lot pull request #25
Opened 2019-04-30 00:22 UTC by AddisonAbercrombie

2019-04-30 00:44 UTC, chuckinchucks requested changes
I feel like we need some kind of key to indicate which texture is which. Other than that and the missing semicolon in app.module.ts, it looks good

2019-04-30 00:44 UTC, chuckinchucks commented on client/smart-lot-client/src/app/app.module.ts
> +import { CookieService } from 'ngx-cookie-service'
line 12 need a semicolon :o

2019-04-30 02:13 UTC, grant-freeman commented
i want to make sure this works with the fade transitions from #23 before i approve this.

2019-05-01 01:25 UTC, slimwizard approved these changes

2019-05-01 01:25 UTC, merged